### ISSUE TITLE
Improve isatty() Windows implementation with Cygwin/Mingw pseudo terminals

### ISSUE THREAD

**Issue by hboutemy** [fusesource/jansi-native#11]
as seen in Jansi issue https://github.com/fusesource/jansi/issues/94, Cygwin and Mingw use pseudo terminals, not real terminals
Then isatty() does not detect the pseudo-terminal
Git has a workaround: https://github.com/git/git/commit/86924838e3d881cda2192fd79ac3a58aad75efd3
```
        /* get pipe name */
 	if (!NT_SUCCESS(NtQueryObject(h, ObjectNameInformation,
 			buffer, sizeof(buffer) - 2, &result)))
 		return;
 	name = nameinfo->Name.Buffer;
 	name[nameinfo->Name.Length] = 0;
 
	/*
	 * Check if this could be a MSYS2 pty pipe ('msys-XXXX-ptyN-XX')
	 * or a cygwin pty pipe ('cygwin-XXXX-ptyN-XX')
	 */
	if ((!wcsstr(name, L"msys-") && !wcsstr(name, L"cygwin-")) ||
			!wcsstr(name, L"-pty"))
		return;
```

This code should be added to Jansi native isatty() implementation for Windows to properly detect (pseudo)terminal with Cygwin and Mingw

**Comment by gnodet** [comment]
The code build, but it does not seem to give the expected results.
When I execute the `CLibrary.isatty(0)` or `CLibrary.isatty(1)` under cygwin, both returns 0.

**Comment by hboutemy** [comment]
did you try to get the value of the terminal name?
this is really the current code in git: https://github.com/git/git/blob/master/compat/winansi.c#L537
