### ISSUE TITLE
Maven Central is missing some version 1.6 JARs

### ISSUE THREAD

**Issue by sschuberth** [fusesource/jansi-native#3]
While Maven Central in general has [version 1.6](http://search.maven.org/#search|gav|1|g%3A%22org.fusesource.jansi%22%20AND%20a%3A%22jansi-native%22), compared to previous releases the platform specific JARs are missing.

**Comment by michael-o** [comment]
They are not. For some reason the project has been retructured and every platform JAR has it's own artifact id. See [here](http://search.maven.org/#search%7Cga%7C1%7Ca%3Ajansi-*).

**Comment by sschuberth** [comment]
Ah, thanks for the info!
