### ISSUE TITLE
Provide FreeBSD native support by default

### ISSUE THREAD

**Issue by michael-o** [fusesource/jansi-native#5]
Only Windows, OS X and Linux are supported. FreeBSD is straight forward, zero changes necessary. Add them by default to Maven Central.

I am willing to provide both 32 and 64 bit shared libraries.

This depends on fusesource/hawtjni#26.

**Comment by dereckson** [comment]
Dependency fusesource/hawtjni#26 is now merged.

**Comment by michael-o** [comment]
@dereckson Now waiting for this update to be included in jansi-native

**Comment by michael-o** [comment]
@chirino Any chance you could take a look? Update the hawtjni plugin and tell what I need to do to provide shared libraries.

**Comment by gnodet** [comment]
I'll include FreeBSD binaries in the upcoming release
