### ISSUE TITLE
Jansi-native libraries are not stack protected

### ISSUE THREAD

**Issue by hs-martinbg** [fusesource/jansi-native#7]
The checksec tool (http://www.trapkit.de/tools/checksec.html) reports that the native libraries are not stack protected. The lack of the protection could lead to change of control flow by overwriting the return address from a function on the stack.

The result of the tool execution was that no canary was found in both linux libraries:
![image001](https://cloud.githubusercontent.com/assets/19729423/22243716/300d4310-e231-11e6-8ba8-8c1fabf76ba3.png)

**Comment by gnodet** [comment]
I'm planning a release soon, so if you can provide any hint on how to fix the problem, I'll happily have a look.
